### ISSUE TITLE
Error tooltips not displaying to user

### ISSUE THREAD

**Issue by yacoubod** [SDHacks/SDHacks2016#34]
### Device (and Operating System)
  
iPhone 5s running iOS 9.3.2, early 2015 mbp 13 running 10.11.6 Beta

### Browser

Safari, Chrome

### Outline of the Issue

"Next" button at the bottom is unresponsive and no errors appear.

### Screenshots

![image](https://cloud.githubusercontent.com/assets/10985176/17278219/9da428fe-570c-11e6-895c-cfb09a81c3b4.png)

### Steps to Reproduce

1. Fill out phone number with more than 10 digits or with letters. Alternatively, don't add major.
2. Click next.

Expected: Error telling user why they cannot proceed.
Actual: No indicators.
  
### Possible Cause

?

**Comment by RedbackThomson** [comment]
Fixed with the implementation of the JQuery Form Validator tool
