### ISSUE TITLE
Unable to submit form or return to first page

### ISSUE THREAD

**Issue by yacoubod** [SDHacks/SDHacks2016#37]
### Device (and Operating System)

early 2015 mbp 13 running 10.11.6 Beta

### Browser

Safari 9.1.2

### Outline of the Issue

Expected: Confirmation or message telling me not to upload large resume. Can return to previous page to remove resume.
Actual: Loading animation displays, disappears after a while. No submission. Cannot go back to first page (back button on form unresponsive).

### Screenshots

![image](https://cloud.githubusercontent.com/assets/10985176/17278977/c4f97f14-571e-11e6-8fa8-b6bec7c241ca.png)

### Steps to Reproduce

1. Fill out first page of form and upload movie for resume.
2. Fill out second page and submit.
  
### Possible Cause

Because I uploaded a video for the resume.

**Comment by RedbackThomson** [comment]
Fixed with the implementation of the Slick carousel package
